tasks:
  - init: > 
      nvm install 12.0 && 
      npm install
    command: npm run dev
ports: 
  - port: 1234
    onOpen: open-preview
vscode:
  extensions:
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - formulahendry.auto-rename-tag@0.1.1:lKCmLIZAiCM0M8AjDnwCLQ==
    - naumovs.color-highlight@2.3.0:6nKORbxgnWjNaN6xACiaQQ==